{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cachestore.serviceAccountName" . }}
  labels:
{{ include "cachestore.labels" . | indent 4 }}
{{- end -}}
